# Developer Configuration - TOML Version
# Maximum information display with all features enabled
# Copy this file to Config.toml or use as reference

[theme]
name = "catppuccin"          # Modern dark theme for developers

# === ALL FEATURES ENABLED ===
[features]
show_commits = true          # Show today's commit activity
show_version = true          # Show Claude Code version
show_submodules = true       # Show git submodule information
show_mcp_status = true       # Show MCP server connectivity
show_cost_tracking = true    # Show detailed cost breakdown
show_reset_info = true       # Show billing block reset timer
show_session_info = true     # Show session information

# === EXTENDED TIMEOUTS FOR DETAILED INFO ===
[timeouts]
mcp = "5s"                   # Longer timeout for MCP discovery
version = "3s"               # Allow time for version check
ccusage = "5s"               # Detailed cost analysis

# === DEVELOPER-FRIENDLY EMOJIS ===
[emojis]
opus = "🧠"                  # Brain for Opus (thinking)
haiku = "⚡"                 # Lightning for Haiku (speed)
sonnet = "🎵"                # Music note for Sonnet (creativity)
default_model = "🤖"         # Robot for other models
clean_status = "✅"          # Green check for clean repo
dirty_status = "📁"          # File folder for dirty repo
clock = "🕐"                 # Clock for time
live_block = "🔥"            # Fire for active billing

# === DETAILED DISPLAY FORMATS ===
[display]
time_format = "%H:%M:%S"     # Include seconds for precision
date_format = "%Y-%m-%d"     # ISO standard date format
date_format_compact = "%Y%m%d"

# === COMPREHENSIVE LABELS ===
[labels]
commits = "Today's Commits:" # Descriptive commit label
repo = "Repository Cost"     # Full repository label
monthly = "30-Day Total"     # Descriptive monthly label
weekly = "Weekly Cost"       # Descriptive weekly label
daily = "Daily Cost"         # Descriptive daily label
mcp = "MCP Servers"          # Full MCP label
version_prefix = "version"   # Full version prefix
submodule = "Submodules:"    # Full submodule label
session_prefix = "Session:"  # Full session prefix
live = "LIVE BILLING"        # Descriptive live label
reset = "Block Reset"        # Full reset label

# === COMPREHENSIVE CACHING ===
[cache]
version_duration = 1800      # 30 minutes - balance freshness/performance
version_file = "/tmp/.claude_version_cache"

# === DETAILED ERROR MESSAGES ===
[messages]
no_ccusage = "ccusage not available"
ccusage_install = "Install ccusage for detailed cost tracking"
no_active_block = "No active billing block"
mcp_unknown = "status unknown"
mcp_none = "no servers"
unknown_version = "version unknown"
no_submodules = "no submodules"

# === ADVANCED FEATURES (Examples for future) ===
[advanced]
warn_missing_deps = true     # Warn about missing dependencies
debug_mode = false           # Disable debug by default
performance_mode = false     # Full features enabled
strict_validation = true     # Strict configuration validation