# Ocean Theme Configuration - TOML Version
# Deep ocean-inspired color palette for a calming development experience
# Copy this file to Config.toml or use as reference

[theme]
name = "custom"              # Custom theme with ocean colors

# === OCEAN-INSPIRED COLOR PALETTE ===
[colors.basic]
# Deep ocean waters and marine life
blue = "\\033[38;2;0;119;190m"      # Deep ocean blue - directories, primary info
teal = "\\033[38;2;0;150;136m"      # Teal depths - commits, counters
cyan = "\\033[38;2;0;188;212m"      # Surface water - model names, secondary info
green = "\\033[38;2;76;175;80m"     # Seaweed green - success states, clean repos
yellow = "\\033[38;2;255;193;7m"    # Sandy shore - warnings, dirty repos
red = "\\033[38;2;220;53;69m"       # Coral red - errors, alerts
white = "\\033[38;2;224;247;250m"   # Sea foam - general text
magenta = "\\033[38;2;72;61;139m"   # Deep sea purple - branches, highlights

[colors.extended]
# Ocean environment colors
orange = "\\033[38;2;255;165;0m"    # Sunset orange - time display
purple = "\\033[38;2;72;61;139m"    # Dark slate blue - version info
light_gray = "\\033[38;2;176;196;222m" # Light steel blue - separators
bright_green = "\\033[38;2;64;224;208m" # Turquoise - MCP servers
gold = "\\033[38;2;255;215;0m"      # Golden sunlight - highlights
pink_bright = "\\033[38;2;255;182;193m" # Light pink - cost tracking
indigo = "\\033[38;2;70;130;180m"   # Steel blue - weekly costs
violet = "\\033[38;2;138;43;226m"   # Blue violet - session info
light_blue = "\\033[38;2;173;216;230m" # Light blue - MCP server names

[colors.formatting]
dim = "\\033[38;2;119;136;153m"     # Light slate gray - dimmed text
italic = "\\033[3m"                 # Italic formatting
strikethrough = "\\033[9m"          # Strikethrough for offline servers
reset = "\\033[0m"                  # Reset formatting

# === OCEAN-THEMED FEATURES ===
[features]
show_commits = true          # Track daily productivity like tides
show_version = true          # Version info like navigation
show_submodules = true       # Submodules like coral formations
show_mcp_status = true       # MCP servers like underwater networks
show_cost_tracking = true    # Cost tracking like treasure management
show_reset_info = true       # Reset info like tide schedules

# === OCEAN-THEMED EMOJIS ===
[emojis]
opus = "🐋"                  # Whale for Opus (deep thinking)
haiku = "🐠"                 # Tropical fish for Haiku (quick & colorful)
sonnet = "🐙"                # Octopus for Sonnet (creative & intelligent)
default_model = "🤖"         # Robot for other models
clean_status = "🌊"          # Ocean wave for clean repo
dirty_status = "🏖️"          # Beach for dirty repo (things washed ashore)
clock = "⏰"                 # Clock for time (lighthouse timing)
live_block = "🔥"            # Fire for active billing

# === OCEAN-THEMED LABELS ===
[labels]
commits = "Waves:"           # Commits like ocean waves
repo = "OCEAN"               # Repository as ocean
monthly = "TIDE"             # Monthly costs like monthly tides
weekly = "CURRENT"           # Weekly costs like ocean currents
daily = "SPLASH"             # Daily costs like daily splashes
mcp = "DEPTHS"               # MCP servers in ocean depths
version_prefix = "nav"       # Version like navigation system
submodule = "REEFS:"         # Submodules like coral reefs
session_prefix = "DIVE:"     # Session like diving session
live = "FLOWING"             # Live costs like flowing water
reset = "LOW TIDE"           # Reset like low tide

# === CALMING TIMEOUTS ===
[timeouts]
mcp = "4s"                   # Gentle timeout like calm waves
version = "3s"               # Steady timeout like steady current
ccusage = "4s"               # Patient timeout like patient sea

# === OCEAN DISPLAY FORMATS ===
[display]
time_format = "%H:%M"        # Simple time like ship's clock
date_format = "%Y-%m-%d"     # Clear date format
date_format_compact = "%Y%m%d"

# === OCEAN CACHE SETTINGS ===
[cache]
version_duration = 3600      # Cache for 1 hour like steady tide
version_file = "/tmp/.claude_ocean_version_cache"

# === OCEAN MESSAGE STYLE ===
[messages]
no_ccusage = "Calm waters"
ccusage_install = "Install ccusage for treasure tracking"
no_active_block = "Still waters"
mcp_unknown = "mysterious depths"
mcp_none = "empty ocean"
unknown_version = "uncharted"
no_submodules = "open sea"